### ISSUE TITLE
Laravel 5.1.30 php artisan config:publish dinesh/bugonemail  not working

### ISSUE THREAD

**Issue by warmwhisky** [dineshrabara/bugonemail#11]
Should this work with Laravel 5.1.30? or did I misunderstand the documentation?

The config file was not generated after `php artisan config:publish dinesh/bugonemail`

Additionally a 500 server error was encountered when I manually created an error. The 500 persisted after manually pasting the config file from the vendor to app/config.

**Comment by dineshrabara** [comment]
publish using php artisan vendor:publish
