### ISSUE TITLE
error in laravel 5 console command

### ISSUE THREAD

**Issue by morganmsk** [dineshrabara/bugonemail#13]
If console command code has error, we can't normal debug it using -v attribute cos error mailer throw error

`
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Session store not set on request.' in /opt/www/releases/20160705113939/vendor/laravel/framework/src/Illuminate/Http/Request.php:852
Stack trace:
#0 /opt/www/releases/20160705113939/vendor/laravel/framework/src/Illuminate/Http/Request.php(523): Illuminate\Http\Request->session()
#1 /opt/www/releases/20160705113939/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(215): Illuminate\Http\Request->old()
#2 /opt/www/releases/20160705113939/vendor/dinesh/bugonemail/src/Dinesh/Bugonemail/BugeException.php(31): Illuminate\Support\Facades\Facade::__callStatic('old', Array)
#3 /opt/www/releases/20160705113939/vendor/dinesh/bugonemail/src/Dinesh/Bugonemail/BugeException.php(31): Illuminate\Support\Facades\Request::old()
#4 /opt/www/releases/20160705113939/vendor/dinesh/bugonemail/src/Dinesh/Bugonemail/BugonemailExceptionHandler.php(27): Dinesh\Bugonemail\BugeException->notifyException(Object(Symfony\Component\Debug\Exceptio in /opt/www/releases/20160705113939/vendor/laravel/framework/src/Illuminate/Http/Request.php on line 852

`

**Comment by dineshrabara** [comment]
i am working on it will be resolve soon

On 5 July 2016 at 17:36, morganmsk notifications@github.com wrote:

> If command has error, we can't normal debug it using -v attribute cos
> error mailer throw error
> 
> `
> PHP Fatal error: Uncaught exception 'RuntimeException' with message
> 'Session store not set on request.' in
> /opt/www/releases/20160705113939/vendor/laravel/framework/src/Illuminate/Http/Request.php:852
> Stack trace:
> #0
> /opt/www/releases/20160705113939/vendor/laravel/framework/src/Illuminate/Http/Request.php(523):
> Illuminate\Http\Request->session()
> #1 https://github.com/dineshrabara/bugonemail/issues/1
> /opt/www/releases/20160705113939/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(215):
> Illuminate\Http\Request->old()
> #2 https://github.com/dineshrabara/bugonemail/pull/2
> /opt/www/releases/20160705113939/vendor/dinesh/bugonemail/src/Dinesh/Bugonemail/BugeException.php(31):
> Illuminate\Support\Facades\Facade::__callStatic('old', Array)
> #3 https://github.com/dineshrabara/bugonemail/pull/3
> /opt/www/releases/20160705113939/vendor/dinesh/bugonemail/src/Dinesh/Bugonemail/BugeException.php(31):
> Illuminate\Support\Facades\Request::old()
> #4 https://github.com/dineshrabara/bugonemail/issues/4
> /opt/www/releases/20160705113939/vendor/dinesh/bugonemail/src/Dinesh/Bugonemail/BugonemailExceptionHandler.php(27):
> Dinesh\Bugonemail\BugeException->notifyException(Object(Symfony\Component\Debug\Exceptio
> in
> /opt/www/releases/20160705113939/vendor/laravel/framework/src/Illuminate/Http/Request.php
> on line 852
> 
> `
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/dineshrabara/bugonemail/issues/13, or mute the thread
> https://github.com/notifications/unsubscribe/ABK9Yqqr0nYydAbD9koJFnxqry8XPuDNks5qSkjOgaJpZM4JFDNO
> .

## 

Regards,

_Dinesh Rabara_
_software Developer_

**Comment by dineshrabara** [comment]
done

please update

**Comment by matthijs-neijenhuijs** [comment]
publishing vendor gives still errors:

matthijs:newfoodelicious matthijs$ php artisan config:publish dinesh/bugonemail 
PHP Fatal error:  Uncaught exception 'Swift_RfcComplianceException' with message 'Address in mailbox given [] does not comply with RFC 2822, 3.6.2.' in /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:347
Stack trace:
#0 /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(263): Swift_Mime_Headers_MailboxHeader->_assertValidAddress('')
#1 /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(106): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)
#2 /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(63): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)
#3 /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderFactory.php(58): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)
#4 /Users/matthijs/www/new in /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php on line 347
PHP Fatal error:  Uncaught exception 'Swift_RfcComplianceException' with message 'Address in mailbox given [] does not comply with RFC 2822, 3.6.2.' in /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:347
Stack trace:
#0 /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(263): Swift_Mime_Headers_MailboxHeader->_assertValidAddress('')
#1 /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(106): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)
#2 /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(63): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)
#3 /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderFactory.php(58): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)
#4 /Users/matthijs/www/new in /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php on line 347
matthijs:newfoodelicious matthijs$ php artisan config:publish dinesh/bugonemail
PHP Fatal error:  Uncaught exception 'Swift_RfcComplianceException' with message 'Address in mailbox given [] does not comply with RFC 2822, 3.6.2.' in /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:347
Stack trace:
#0 /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(263): Swift_Mime_Headers_MailboxHeader->_assertValidAddress('')
#1 /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(106): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)
#2 /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(63): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)
#3 /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderFactory.php(58): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)
#4 /Users/matthijs/www/new in /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php on line 347
PHP Fatal error:  Uncaught exception 'Swift_RfcComplianceException' with message 'Address in mailbox given [] does not comply with RFC 2822, 3.6.2.' in /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:347
Stack trace:
#0 /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(263): Swift_Mime_Headers_MailboxHeader->_assertValidAddress('')
#1 /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(106): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)
#2 /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(63): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)
#3 /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderFactory.php(58): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)
#4 /Users/matthijs/www/new in /Users/matthijs/www/newfoodelicious/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php on line 347

**Comment by dineshrabara** [comment]
Please use vendor publish
