### ISSUE TITLE
on Post not getting Server/Data

### ISSUE THREAD

**Issue by Arametheus** [dineshrabara/bugonemail#15]
So when we have an Error and it is thru Post. 
I get the Post Data and the Error but we do not get any other section including the Server/Data Section.  

is there a reason for this??

**Comment by dineshrabara** [comment]
just put file in resources/views/vendor/bugonemail/email


[notifyException.blade.php.tar.gz](https://github.com/dineshrabara/bugonemail/files/639254/notifyException.blade.php.tar.gz)
