### ISSUE TITLE
Error Handler order

### ISSUE THREAD

**Issue by github-db** [dineshrabara/bugonemail#6]
The [official laravel docs on errors](http://laravel.com/docs/4.2/errors) suggests that, to return a custom error page response, the `App::error()` method on `app/start/global.php` should be edited. Eg.:

```php
App::error(function(Exception $exception, $code){
    Log::error($exception);

    return Response::view('errors.500');
});
```

If this method returns anything, the handler registered by this package __will never be called__.

This is a problem because live environments always have a user-friendly error page, and we definitely need those emails sent to us.

My workaround was to move my error handler to a `ServiceProvider`, and register that provider last in my `config/app.php` `'providers'` array.

```php
'providers' => array(
    // Register the bugonemail's error handler
    'Dinesh\Bugonemail\BugonemailServiceProvider',
    // Register the application's error handler (this one returns a view)
    'Acme\MyApp\ErrorHandlingServiceProvider'
)
```

This works, but it would be nice if the package could work out-of-the-box with the default Laravel way.

On that subject, I feel that what this package is doing should not be considered an error handler. I feel this could work better as an __event listener__ approach. Laravel fires up a few of those on errors, so we could hook to that!

**Comment by dineshrabara** [comment]
Hi..

you can use  BugeException::notifyException($exception)

manual call
